input: .
output: .retype
url: architechshop.co.uk # Add your website address here
branding:
  title: Architech
  label: Support
  logo: static/logo2.png
poweredByRetype: true # Set to false to remove the Powered by Retype branding.
                      # A Retype Pro license is required.
                      # See: https://retype.com/pro
links:
  - text: Getting Started
    link: https://retype.com/guides/getting-started/
footer:
  copyright: "&copy; Copyright . All rights reserved."
  
  name: Publish Retype powered website to GitHub
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  publish:
    name: Publish to the retype branch

    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - uses: retypeapp/action-build@latest

      - uses: retypeapp/action-github-pages@latest
        with:
          branch: retype
          update-branch: true